// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0UswQ98BU27XfQgUSi2nHmsetSUzaPo',
    appId: '1:450918988769:web:589325a9cc0afc33f1f0a0',
    messagingSenderId: '450918988769',
    projectId: 'freightflow-6ccc9',
    authDomain: 'freightflow-6ccc9.firebaseapp.com',
    storageBucket: 'freightflow-6ccc9.firebasestorage.app',
    measurementId: 'G-24E9V778HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_B9eHjlZ12mUqXXFavU5lRhpuHGXDVvE',
    appId: '1:450918988769:android:f40332389cb0de2cf1f0a0',
    messagingSenderId: '450918988769',
    projectId: 'freightflow-6ccc9',
    storageBucket: 'freightflow-6ccc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMDvEzFoiq0av-AX7ord0Ee2ParDvkX24',
    appId: '1:450918988769:ios:e6c84e0531f11d00f1f0a0',
    messagingSenderId: '450918988769',
    projectId: 'freightflow-6ccc9',
    storageBucket: 'freightflow-6ccc9.firebasestorage.app',
    iosBundleId: 'com.example.freightFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMDvEzFoiq0av-AX7ord0Ee2ParDvkX24',
    appId: '1:450918988769:ios:e6c84e0531f11d00f1f0a0',
    messagingSenderId: '450918988769',
    projectId: 'freightflow-6ccc9',
    storageBucket: 'freightflow-6ccc9.firebasestorage.app',
    iosBundleId: 'com.example.freightFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp0UswQ98BU27XfQgUSi2nHmsetSUzaPo',
    appId: '1:450918988769:web:8fd016ab55c154e6f1f0a0',
    messagingSenderId: '450918988769',
    projectId: 'freightflow-6ccc9',
    authDomain: 'freightflow-6ccc9.firebaseapp.com',
    storageBucket: 'freightflow-6ccc9.firebasestorage.app',
    measurementId: 'G-T9GRF073CR',
  );
}
